---

- name: Install EPEL
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install Webtatic
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present
