---

  - name: Add New Relic Repo
    yum: name=http://yum.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm state=present

  - name: Install New Relic
    yum: name={{ item }} state=latest
    with_items:
      - newrelic-php5
      - newrelic-sysmond

  - name: Install New Relic PHP
    command: newrelic-install install
    environment:
      NR_INSTALL_SILENT: true

  - name: Install Server License
    command: nrsysmond-config --set license_key={{newrelic_license}}

  - name: Start New Relic
    service: name=newrelic-sysmond state=restarted

  - name: Install App License
    ini_file: dest=/etc/php.d/newrelic.ini section=newrelic option="{{ item.option }}" value="\"{{ item.value }}"\"
    with_items:
      - { option: "newrelic.appname", value: "MailHops API" }
      - { option: "newrelic.license", value: "{{ newrelic_license }}" }
      - { option: "newrelic.process_host.display_name", value: "{{ inventory_hostname }}" }

  - name: Copy newrelic.ini
    copy: src=/etc/php.d/newrelic.ini dest=/etc/php-fpm.d/newrelic.ini remote_src=yes
    notify:
     - restart nginx
     - restart php-fpm
